apiVersion: v1

kind: catelogue

metadata:
  name: catelogue
  namespace: roboshop
  labels:
    purpose: catelogue
    env: dev

data:
  COURSE: "devops with aws"
  duration: "120 hrs"
  trainer: "bharath kumar"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catelogue
  namespace: roboshop
  labels:
    component: catelogue
    project: roboshop
    tier: app

spec:
  replicas: 1

  selector:
    matchLabels:
      component: catelogue
      project: roboshop
      tier: app

  template:
    metadata:
      labels:
        component: catelogue
        project: roboshop
        tier: app

    spec:
      containers:
        - name: catelogue
          image: bharathkumarots/catelogue:v1

---
apiVersion: v1
kind: Service

metadata:
  name: catelogue
  namespace: roboshop
  labels:
    component: catelogue
    project: roboshop
    tier: app

spec:
  selector:
    component: catelogue
    project: roboshop
    tier: app

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080